language: python

python:
    - 2.7
    # - 3.6

# command to install dependencies
install:
  - pip install $(grep Cython requirements.txt)
  - pip install -r requirements.txt

script: python -m unittest discover --start-directory=tests/
