sudo: required

language: generic

# before_script:
#     - "export DISPLAY=:99.0"
#     - "sh -e /etc/init.d/xvfb start"
#     - sleep 3 # give xvfb some time to start

services:
  - docker

env:
  - TAG=pywallet-linux DOCKERFILE=dockerfiles/Dockerfile-linux COMMAND='make test'
  - TAG=pywallet-android DOCKERFILE=dockerfiles/Dockerfile-android COMMAND='buildozer android debug'

before_script:
    - docker build --tag=$TAG --file=$DOCKERFILE --build-arg TRAVIS .

script:
    - travis_wait 30 docker run $TAG $COMMAND
